language: go

sudo: false

go:
  - 1.5
  - 1.6
  - tip

before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/go-playground/overalls

before_script:
  - mv ${TRAVIS_HOME}/gopath/src/github.com/{${TRAVIS_REPO_SLUG%%/*},matthieugrieger}
  - cd ${TRAVIS_HOME}/gopath/src/github.com/matthieugrieger/mumbledj

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - GO15VENDOREXPERIMENT="1"
