language: go

sudo: false

go:
  - 1.5
  - 1.6
  - tip

before_script:
  - mv ${TRAVIS_HOME}/gopath/src/github.com/{${TRAVIS_REPO_SLUG%%/*},matthieugrieger}
  - cd ${TRAVIS_HOME}/gopath/src/github.com/matthieugrieger/mumbledj

script:
  - make

env:
  global:
    - GO15VENDOREXPERIMENT="1"
